
(require 'color-theme)

(defvar butter1 "#fce94f")
(defvar butter2 "#edd400")
(defvar butter3 "#c4a000")
(defvar orange1 "#fcaf3e")
(defvar orange2 "#f57900")
(defvar orange3 "#ce5c00")
(defvar choc1   "#e9b96e")
(defvar choc2   "#c17d11")
(defvar choc3   "#8f5902")
(defvar cham1   "#8ae234")
(defvar cham2   "#73d216")
(defvar cham3   "#4e9a06")
(defvar blue1   "#729fcf")
(defvar blue2   "#3465a4")
(defvar blue3   "#204a87")
(defvar plum1   "#ad7fa8")
(defvar plum2   "#75507b")
(defvar plum3   "#5c3566")
(defvar red1    "#ef2929")
(defvar red2    "#cc0000")
(defvar red3    "#a40000")
(defvar alum1   "#eeeeec")
(defvar alum2   "#d3d7cf")
(defvar alum3   "#babdb6")
(defvar alum4   "#888a85")
(defvar alum5   "#555753")
(defvar alum6   "#2e3436")

;;;###autoload
(defun color-theme-tango ()
  "A color theme based on Tango Palette."
  (interactive)
  (setq frame-background-mode 'dark)
  (color-theme-install
   `(color-theme-tango
     ((background-color . ,alum6)
      (background-mode . dark)
      (border-color . ,alum4)
      (cursor-color . ,butter1)
      (foreground-color . ,alum2)
      (mouse-color . ,cham1))
     ((help-highlight-face . underline)
      (ibuffer-dired-buffer-face . font-lock-function-name-face)
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face . font-lock-type-face)
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face))
     (border                       ((t (:background ,alum4))))
     (fringe                       ((t (:background ,alum6))))
     (mode-line                    ((t (:foreground ,alum1 :background ,alum5))))
     (region                       ((t (:background ,alum5))))
     (highlight                    ((t (:background ,alum6))))
     (font-lock-builtin-face       ((t (:foreground ,blue1))))
     (font-lock-comment-face       ((t (:foreground ,alum4))))
     (font-lock-constant-face      ((t (:foreground ,cham1))))
     (font-lock-doc-face           ((t (:foreground ,alum4))))
     (font-lock-keyword-face       ((t (:foreground ,blue1))))
     (font-lock-string-face        ((t (:foreground ,plum1))))
     (font-lock-type-face          ((t (:foreground ,cham1))))
     (font-lock-variable-name-face ((t (:foreground ,alum2))))
     (font-lock-warning-face       ((t (:foreground ,orange2))))
     (font-lock-function-name-face ((t (:foreground ,butter2))))
     (comint-highlight-prompt      ((t (:foreground ,cham1))))
     (isearch                      ((t (:background ,orange2 :foreground ,alum6))))
     (isearch-lazy-highlight-face  ((t (:foreground ,alum6 :background ,choc1))))
     (show-paren-match-face        ((t (:foreground ,alum6 :background ,cham2))))
     (show-paren-mismatch-face     ((t (:background ,plum1 :foreground ,alum6))))
     (minibuffer-prompt            ((t (:foreground ,blue1))))
     (info-xref                    ((t (:foreground ,blue1))))
     (info-xref-visited            ((t (:foreground ,plum1))))
     (compilation-warning          ((t (:foreground ,butter2))))
     (compilation-info             ((t (:foreground ,alum2))))
     )))

(provide 'color-theme-tango)
